name: hci_final_project
description: "A new Flutter project."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.7
  shared_preferences: ^2.1.1
  shared_preferences_web: ^2.0.0
  confetti: ^0.7.0
  lottie: ^3.3.2
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/onboardingscreen/welcome.png
    - assets/onboardingscreen/subject.png
    - assets/onboardingscreen/exam.png
    - assets/onboardingscreen/badge.png
    - assets/onboardingscreen/track.png
    - assets/onboardingscreen/maths.png
    - assets/icons/linear.png
    - assets/icons/calculus.png
    - assets/icons/physics.png
    - assets/icons/chemistry.png
    - assets/icons/star.png
    - assets/
    - assets/splash.png
    - assets/avatars/
flutter_native_splash:
  color: "#d5deef"
  image: assets/splash.png
  fullscreen: true

  android_12:
    color: "#42a5f5"
    icon_background_color: "#111111"